project_id = "zevuqoiqmlkudholotmp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[[functions]]
name = "create-checkout"
verify_jwt = true

[[functions]]
name = "check-subscription"
verify_jwt = true